apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Node Feature Discovery
  - nfd-ns.yaml
  - nfd-operatorgroup.yaml
  - nfd-subscription.yaml
  # NVIDIA GPU Operator
  - gpu-operator-ns.yaml
  - gpu-operatorgroup.yaml
  - nvidia-gpu-subscription.yaml
