apiVersion: nfd.openshift.io/v1
kind: NodeFeatureDiscovery
metadata:
  name: nfd-instance
spec:
  instance: ''
  operand:
    # image: to get the image run and copy here (if nul leave empty):
    #   oc get csv -n openshift-nfd -o json | jq -r '.items[0].metadata.annotations["alm-examples"]' | tr -d '\000-\037' | jq -r '.[] | select(.kind == "NodeFeatureDiscovery") | .spec.operand.image'
    servicePort: 12000
  prunerOnDelete: false
  topologyUpdater: false
  workerConfig:
    configData: |
      core:
        sleepInterval: 60s
      sources:
        pci:
          deviceClassWhitelist:
            - "02"
            - "03"
            - "0200"
            - "0207"
            - "12"
          deviceLabelFields:
            - "vendor"